# Site settings
title: andreas offenhaeuser
description: resume and portfolio
favicon: favicon.ico
#baseurl: https://anoff.io
google_analytics: UA-93890295-2

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Andreas Offenhaeuser
  title: Cloud Solution Architect
  address: Stuttgart, Germany
  email: offenhaeuser#gmail.com
  link: http://anoff.io
  github: anoff
  linkedin: anoff
  twitter: an0xff
  gavatar: assets/img/iceicesquare.jpg
