# Site settings
title: andreas offenhaeuser
description: resume and portfolio
favicon: favicon.ico
#baseurl: https://anoff.io
google_analytics: UA-93890295-2

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Andreas Offenhaeuser
  title: Cloud Solution Architect
  address: Stuttgart, Germany
  email: offenhaeuser#gmail.com
  link: http://anoff.io
  weibo:
  github: anoff
  linkedin: anoff
  twitter: an0xff
  gavatar: assets/img/iceicesquare.jpg
  stackoverflow:
  workHistory:
    - work2016:
      company: Robert Bosch GmbH
      location: Stuttgart, Germany
      title: Solution Architect
      started: 2016
      duration: (2016 - Present)
      description: Developing solutions for connected services using latest technologies like Docker, Gitlab & nodeJS. My job is to make sure that our different products keep a common technology stack, evaluate new technologies with regard to compatibility and identify potential for further collaboration within the company.
    - work2014:
      company: Robert Bosch GmbH
      location: Stuttgart, Germany
      title: Backend developer connected vehicle
      started: 2014
      duration: (2014 - 2016)
      description: Responsible to design and build a prototype system for a connected vehicle service. I lead a team of up to five to bring a fullstack solution featuring nodeJS and angularJS deployed on a single VM to live.
    - work2012:
      company: Robert Bosch GmbH
      location: Stuttgart, Germany
      title: Function developer for driver monitoring
      started: 2012
      duration: (2012 - 2014)
      description: Today it would be called a (big) data analysts job - back then I was responsible to develop a simulation framework capable of handling multiple thousands kilometers of test data to evaluate algorithm performance, improve data quality, come up with proper loss functions as well as implement audit proof change management functionality. Embedded in an overall project team myself and one other colleague used this framework to advance driver monitoring solutions for global OEMs on a functional level.
    - work2010:
      company: Robert Bosch GmbH
      location: Stuttgart, Germany
      title: Test manager for driver monitoring software
      started: 2010
      duration: (2010 - 2012)
      description: My job as test manager included developing a ISO26262 compliant test plan to cover tests from unit to system level. For tests on system level I was responsible to design, implement and contract a new framework to execute hardware in the loop simulation for automotive ECUs.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: German
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Beginner
  programmingSkills:
    - skill1:
      name: nodeJS
      percentage: 100%
    - skill2:
      name: JavaScript
      percentage: 90%
    - skill3:
      name: Python
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 30%
