# Site settings
title: andreas offenhaeuser
description: resume and portfolio
favicon: favicon.ico
#baseurl: https://anoff.io
google_analytics: UA-93890295-2

# Build settings
markdown: kramdown

exclude: [vendor]

